= 폰트 추가

이 페이지는 UI에 새 글꼴을 추가하는 방법을 설명합니다. 이 지침은 기본 UI를 포크하고 사용자 정의할 수 있다고 가정합니다.

세 가지 단계가 있습니다:

1. UI 프로젝트에 글꼴 추가
2. 스타일시트에 font-face 선언 추가
3. 스타일시트에서 새 글꼴 사용

font-face 선언에서 글꼴 파일을 참조하는 방법은 글꼴을 관리하기로 결정한 방식에 따라 다릅니다. npm으로 글꼴을 관리하거나 수동으로 다운로드하여 UI 프로젝트에 직접 추가할 수 있습니다. 다음 섹션에서는 각 접근 방식을 차례로 설명합니다.

== npm 관리

npm(또는 Yarn)을 사용하여 글꼴을 관리할 수 있습니다. 이 접근 방식을 사용하면 UI 프로젝트에 글꼴 파일을 직접 저장할 필요가 없습니다. 다음은 관련된 단계입니다.

. npm(또는 Yarn)을 사용하여 패키지에서 글꼴 파일을 설치합니다(예: xref:https://www.npmjs.com/package/typeface-open-sans[typeface-open-sans])
+
[source,console]
----
$ npm i --save typeface-open-sans
----

. __src/css__에 해당하는 CSS 파일을 추가합니다(예:__ typeface-open-sans.css__)

. 해당 파일에서 글꼴 페이스를 선언합니다:
+
[source,css]
----
@font-face {
  font-family: "Open Sans";
  font-style: normal;
  font-weight: 400;
  src:
    local("Open Sans"),
    local("Open Sans-Regular"),
    url(~typeface-open-sans/files/open-sans-latin-400.woff) format("woff")
}
----
+
Gulp 빌드는 `~` URL 접두사를 인식하고 npm 패키지에서 빌드 폴더(따라서 번들)로 글꼴을 복사합니다.
+
스타일시트에서 사용하려는 글꼴의 각 글꼴 두께와 스타일 조합(예: `font-weight: 500` + `font-style: italic`)에 대해 하나의 @font-face를 정의해야 합니다.

. 방금 만든 typeface CSS 파일을 주 스타일시트인 __src/css/site.css__로 가져옵니다(다른 typeface 가져오기 옆에):
+
[source,css]
----
@import "typeface-open-sans.css";
----

. 해당 패키지에서 사용하려는 각 글꼴 스타일과 두께에 대해 이전 단계를 반복합니다.

. CSS를 변경하여 새로 가져온 글꼴을 사용합니다:
+
[source,css]
----
html {
  font-family: "Open Sans", sans;
}
----
+
TIP: 기본 UI를 기반으로 작업하는 경우 __src/css/vars.css__에 정의된 변수를 사용하여 글꼴 패밀리를 정의하거나 업데이트할 수 있습니다.

. UI를 미리 보기하여 새 글꼴을 테스트합니다:
+
[source,console]
----
$ npx gulp preview
----

새 글꼴이 보이면 UI에 성공적으로 추가한 것입니다. 확실하지 않은 경우 브라우저의 개발자 도구에서 페이지의 모든 글꼴 섹션을 찾아 글꼴이 로드되었는지 확인하세요.

== 수동

글꼴을 추가하는 더 간단한 방법은 프로젝트에 직접 저장하는 것입니다. 다음은 관련된 단계입니다.

. 글꼴 파일을 다운로드하고 __src/font__ 폴더에 추가합니다. 이 폴더가 없으면 생성하세요.

. __src/css__에 해당하는 CSS 파일을 추가합니다(예: __typeface-open-sans.css__)

. 해당 파일에서 글꼴 페이스를 선언합니다:
+
[source,css]
----
@font-face {
  font-family: "Open Sans";
  font-style: normal;
  font-weight: 400;
  src:
    local("Open Sans"),
    local("Open Sans-Regular"),
    url(../font/open-sans-latin-400.woff) format("woff")
}
----
+
경로가 __src/css__ 폴더에서 __src/font__ 폴더로 시작하는 상대 경로임에 주의하세요.
스타일시트에서 사용하려는 글꼴의 각 글꼴 두께와 스타일 조합(예: `font-weight: 500` + `font-style: italic`)에 대해 하나의 ``@font-face``를 정의해야 합니다.

. 방금 만든 typeface CSS 파일을 주 스타일시트인 __src/css/site.css__로 가져옵니다(다른 typeface 가져오기 옆에):
+
[source,css]
----
@import "typeface-open-sans.css";
----

. 사용하려는 각 글꼴 스타일과 두께에 대해 이전 단계를 반복합니다.

. CSS를 변경하여 새로 가져온 글꼴을 사용합니다:
+
[source,css]
----
html {
  font-family: "Open Sans", sans;
}
----
+
TIP: 기본 UI를 기반으로 작업하는 경우 __src/css/vars.css__에 정의된 변수를 사용하여 글꼴 패밀리를 정의하거나 업데이트할 수 있습니다.

. UI를 미리 보기하여 새 글꼴을 테스트합니다:

[source,console]
----
$ npx gulp preview
----

새 글꼴이 보이면 UI에 성공적으로 추가한 것입니다. 확실하지 않은 경우 브라우저의 개발자 도구에서 페이지의 모든 글꼴 섹션을 찾아 글꼴이 로드되었는지 확인하세요.