= 정적 파일 추가

정적 UI 파일은 UI에서 제공하여 사이트에 직접 복사되는 모든 파일입니다. 정적 파일의 일반적인 예는 파비콘 이미지입니다. 추가 정적 파일을 추가하는 한 가지 방법은 Antora 플레이북에 정의된 보조 UI를 사용하는 것입니다. 이 문서에서는 대신 UI 번들에서 정적 파일을 추가하는 방법을 설명합니다. UI 번들에 정적 파일을 넣는 주요 이점은 보조 UI를 사용하여 프로젝트별로 추가할 필요 없이 여러 프로젝트에서 공유할 수 있다는 것입니다.

== Antora가 정적 UI 파일을 식별하는 방법

Antora는 UI 번들의 최상위 수준에서 여러 게시 불가능한 파일과 폴더를 인식합니다. 이 목록은 __helpers__, __layouts__, __partials__ 폴더와 선택적 __ui.yml__ 파일로 구성됩니다. 이러한 파일과 폴더는 UI 번들에 존재하지만 사이트의 출력 디렉토리에 복사되지 않습니다. 즉, 이들은 정적 파일이 아닙니다. 대신, HTML 페이지를 구성하거나 구성에 사용됩니다.

Antora가 인식하지 못하는 UI 번들의 모든 파일이나 폴더는 정적으로 분류됩니다. 정적 파일과 폴더는 UI 번들에서 UI 출력 디렉토리(예: _) 아래의 사이트 출력 디렉토리로 자동으로 복사되며, UI 번들에서의 파일의 상대 경로를 유지합니다. 점(즉, 숨김)으로 시작하는 모든 파일이나 폴더는 정적 파일로 명시적으로 나열되지 않는 한 무시됩니다.

Antora의 기본 UI에는 이미 여러 개의 고유한 정적 폴더가 있습니다. 이 목록에는 css, font(생성됨), img, js 폴더가 포함됩니다.

기본 UI에서는 사용되지 않지만, UI 빌드는 __src/static__이라는 또 다른 정적 폴더를 인식합니다. UI 빌드가 이 폴더 내에서 중첩된 파일을 포함한 모든 파일을 찾으면 하위 폴더를 유지하면서 UI 번들의 루트로 직접 복사합니다.

이 기능을 활용하여 UI 번들에 여러 개의 새로운 정적 파일을 추가해 보겠습니다. 먼저 __src__ 아래에 __static__이라는 폴더를 만듭니다:

[source]
----
$ mkdir src/static
----

이제 숨김 파일을 포함하여 여러 파일을 __src/static__ 폴더에 추가해 보겠습니다. 다음은 이러한 새 파일의 위치를 보여주는 파일 트리입니다:

[source]
----
src/
  static/
    about/
      notice.txt
    .DS_Store
    favicon.ico
    favicon.png
----

이제 정적 파일이 UI 프로젝트에서 게시된 사이트로 어떻게 흐르는지 살펴보겠습니다. UI 프로젝트 내에서 이러한 파일이 있는 위치부터 시작하겠습니다(여기에는 정적이 아닌 파일은 표시되지 않음):

.UI 프로젝트
[source]
----
src/
  ...
  css/
    ...
  img/
    back.svg
    ...
  js/
    ...
  static/
    about/
      notice.txt
    .DS_Store
    favicon.ico
    favicon.png
----

UI 빌드는 다음과 같이 파일을 UI 번들로 조립합니다:

.UI 번들의 내용
[source]
----
...
css/
  site.css
font/
  roboto-latin-400-italic.woff
  ...
img/
  back.svg
  ...
js/
  site.js
about/
  notice.txt
.DS_Store
favicon.ico
favicon.png
----

NOTE: font 폴더는 UI 빌드에 의해 도입됩니다.

Antora 빌드에서 이 UI 번들을 사용할 때, 사이트의 출력 디렉토리 내용은 다음과 같습니다:

.사이트 출력 디렉토리의 내용
[source]
----
_/
  css/
    site.css
  font/
    roboto-latin-400-italic.woff
    ...
  img/
    back.svg
    ...
  js/
    site.js
  about/
    notice.txt
  favicon.ico
  favicon.png
component-a/
  ...
sitemap.xml
...
----

앞서 언급했듯이, 정적 파일은 기본적으로 게시된 사이트의 UI 출력 디렉토리(예: _)에 복사됩니다. 이 디렉토리에서 기본 UI에서 제공하는 정적 폴더인 css, font, img, js 폴더를 볼 수 있습니다. 또한 첫 번째 단계에서 UI 프로젝트에 추가한 __about__ 폴더와 __favicon__ 파일도 볼 수 있습니다. __helpers__, __partials__, __layouts__ 폴더는 정적 파일이 아니므로 보이지 않습니다. 또한 __.DS_Store__ 파일은 숨김 파일이므로 보이지 않습니다.

정적 파일을 UI 출력 디렉토리에 두고 싶다면 더 이상 할 일이 없습니다. 모든 정적 파일 또는 일부를 사이트 루트로 이동하려면 추가 구성을 통해 승격해야 합니다.

== 정적 파일 승격하기

특정 정적 파일을 사이트의 루트로 승격하려면 이를 식별해야 합니다. __ui.yml__ 파일을 사용하여 이를 식별합니다. UI 디스크립터라고 불리는 이 파일은 UI의 동작을 구성하는 데 사용됩니다. UI 디스크립터는 UI 번들의 루트에 위치해야 합니다.

UI 디스크립터에는 우리가 관심 있는 필수 키인 ``static_files``가 하나 있습니다. ``static_files`` 키는 UI 출력 디렉토리에서 사이트 루트(즉, 사이트 출력 디렉토리)로 승격되어야 하는 파일을 식별합니다. 승격하려는 파일은 배열로 지정해야 하며, 각 항목은 UI 번들의 정확한 상대 경로이거나 상대 경로의 glob입니다. 정확한 경로 또는 경로 glob은 폴더가 아닌 파일과 일치해야 합니다. 암시적 정적 파일과 달리 승격된 정적 파일은 점으로 시작할 수 있습니다(따라서 무시되지 않음).

승격할 정적 파일을 구성하려면 UI 프로젝트에서 __src/ui.yml__ 파일을 만드는 것부터 시작하세요. 이 파일이 존재하면 UI 빌드는 이 파일을 UI 번들의 루트로 복사합니다.

다음으로 이 파일에 static_files 키를 추가하고 __favicon.ico__ 파일에 대한 항목을 추가합니다. 이 항목은 UI가 파비콘을 사이트 루트로 승격하도록 구성합니다.

.src/ui.yml
[source,yaml]
----
static_files:
- favicon.ico
----

다른 접미사나 파일 확장자를 가진 여러 파비콘 파일이 있는 경우 와일드카드(일명 glob)를 사용하여 모두 일치시킬 수 있습니다.

.src/ui.yml
[source,yaml]
----
static_files:
- favicon*
----

이 구성을 통해 Antora는 UI 번들에서 파비콘 이미지를 읽고 사이트 루트에 복사합니다. 식별되지 않은 정적 파일은 여전히 UI 출력 디렉토리에 복사됩니다. 위의 __ui.yml__의 결과는 다음과 같습니다:

.사이트 출력 디렉토리의 내용
[source]
----
_/
  css/
    site.css
  font/
    roboto-latin-400-italic.woff
    ...
  img/
    back.svg
    ...
  js/
    site.js
  about/
    notice.txt
component-a/
favicon.ico
favicon.png
  ...
sitemap.xml
...
----

승격된 파비콘 파일이 이제 UI 출력 디렉토리 내부가 아닌 사이트 루트에 있다는 점에 주목하세요. 그러나 about 폴더는 여전히 UI 출력 디렉토리 내부에 있습니다. 이것도 승격해 보겠습니다.

마지막 경로 세그먼트에 와일드카드 pass:[*]를 사용하여 폴더의 모든 파일을 식별할 수 있습니다(예: __folder/pass:[*]__). 마지막 경로 세그먼트에 와일드카드 pass:[**]를 사용하여 모든 깊이의 폴더에 있는 모든 파일을 식별할 수 있습니다(예: __folder/pass:[**]__). 폴더 일치는 효과가 없습니다(예: folder). 와일드카드는 숨김 파일과 절대 일치하지 않습니다. 숨김 파일은 항상 정확한 경로 일치를 사용하여 작성해야 합니다.

__ui.yml__ 파일의 ``static_files`` 키에 와일드카드 일치를 추가하여 __about__ 폴더의 모든 파일도 승격해 보겠습니다.

.src/ui.yml
[source,yaml]
----
static_files:
- favicon*
- about/*
----

이 구성을 사용하면 __about__ 폴더가 UI 출력 디렉토리 내부가 아닌 파비콘 파일 옆의 사이트 루트에 위치하게 됩니다. __about__ 폴더가 내용뿐만 아니라 폴더 자체도 복사된다는 점에 주목하세요.

이제 정적 파일이 원하는 위치에 있으므로 HTML 페이지에서 이를 참조하는 방법을 살펴보겠습니다.

== 정적 파일 사용하기

사이트에 정적 파일을 추가할 때 종종 어딘가에서 이를 참조해야 합니다. 파비콘 이미지의 경우 HTML 페이지의 <head>에서 참조해야 합니다. 승격된 정적 파일을 참조하는 경우 접두사 ``{{{siteRootPath}}}``를 사용합니다. 그렇지 않으면 접두사 ``{{{uiRootPath}}}``를 사용합니다.

__src/partials/head-icons.hbs__ 부분을 업데이트하여 사이트 루트의 승격된 파비콘 이미지를 참조해 보겠습니다.

.src/partials/head-icons.hbs
[source,handlebars]
----
    <link rel="icon" href="{{{siteRootPath}}}/favicon.ico" type="image/x-icon">
----

gulp bundle로 UI를 다시 빌드하세요. 이제 UI 번들에서 제공하는 파비콘 이미지가 사이트에 있는 것을 볼 수 있습니다.