= 코드 블록

이 페이지는 코드 블록의 일부 스타일과 동작, 그리고 사용자 정의 UI에서 이를 지원하는 방법을 설명합니다.

AsciiDoc에서 코드 블록은 소스 블록과 리스팅 블록으로 불립니다. 소스 블록은 소스 언어가 정의된 리스팅 블록입니다(예: javascript). AsciiDoc의 소스 블록과 Antora에서 사용되는 방법에 대해 자세히 알아보려면 소스 블록을 참조하세요.

독자들은 일반적으로 소스 블록이 구문 강조와 함께 표시되기를 기대하므로, 여기서부터 시작하겠습니다.

== 구문 강조

Antora는 기본적으로 AsciiDoc 프로세서에서 highlight.js를 구문 강조기로 사용합니다.

구문 강조를 끄고 싶다면 Antora 플레이북에서 `source-highlighter` 속성을 해제할 수 있습니다.

[source,yaml]
----
asciidoc:
  attributes:
    source-highlighter: ~
----

값을 소프트 해제하는 경우(즉, 값을 `false`로 설정), 개별 페이지에서 선택적으로 구문 강조를 다시 켤 수 있습니다.

기본적으로 Antora는 지원 에셋 파일의 크기를 최소화하기 위해 제한된 언어 세트를 강조 표시합니다. 그러나 자체 UI 번들에서 언어 지원을 추가하거나 제거할 수 있습니다. 다음 단계를 따르세요:

. UI 프로젝트로 전환합니다.
. __src/js/vendor/highlight.bundle.js__ 파일을 엽니다.
. `registerLanguage` 문을 추가하거나 제거합니다.

예를 들어, AsciiDoc 구문 강조를 추가하려면 다음 줄을 추가하세요:

[source,js]
----
  hljs.registerLanguage('asciidoc', require('highlight.js/lib/languages/asciidoc'))
----

highlight.js에서 지원하는 언어여야 한다는 점을 기억하세요. 지원되는 언어와 약어를 확인하려면 GitHub의 프로젝트에서 languages 폴더를 확인하세요.

== 클립보드에 복사

이 페이지는 기본 UI 사용 시 소스 블록에 추가되는 클립보드 복사 기능에 대해 설명합니다.

=== 소스 블록

기본 UI는 모든 소스 블록에 클립보드 버튼을 자동으로 추가하고 해당 동작을 지원하는 데 필요한 CSS와 JavaScript를 제공합니다. 클립보드 버튼은 마우스가 블록 위로 호버될 때 언어 레이블 옆에 나타납니다. 사용자가 클립보드 버튼을 클릭하면 소스 블록의 내용이 사용자의 클립보드에 복사되고 알림 오버레이가 잠시 표시됩니다.

아래에서 이 동작을 시도해 볼 수 있습니다:

[source,ruby]
----
puts 'Take me to your clipboard!'
----

IMPORTANT: 클립보드에 복사 기능은 로컬 사이트나 https(SSL)를 통해 호스팅되는 사이트에서만 작동합니다. 안전하지 않은 사이트(http)에서는 클립보드 API를 사용할 수 없으므로 클립보드에 복사 기능이 작동하지 않습니다. 이 경우 동작이 자연스럽게 저하되어 사용자는 클립보드 버튼이나 오류를 보지 않게 됩니다.

=== 콘솔 블록

기본 UI는 모든 콘솔 블록에도 클립보드 버튼을 추가합니다. 콘솔 블록은 `$`로 시작하는 리터럴 단락이거나 언어가 ``console``인 소스 블록입니다.

기본 UI에서 제공하는 스크립트는 각 줄 시작 부분의 ``$`` 프롬프트를 자동으로 제거하고 줄을 ``&&``로 연결합니다. 다중 줄 콘솔 명령의 클립보드에 복사에서 언어가 ``console``이고 각 줄이 ``$``로 시작하므로 콘솔 복사-붙여넣기 로직이 트리거됩니다.

==== 다중 줄 콘솔 명령의 클립보드에 복사

[source]
--
[source,console]
----
$ mkdir example
$ cd example
----
--

사용자가 클립보드에 복사 버튼을 사용하면 표시된 리터럴 텍스트 대신 결합된 명령 ``mkdir example && cd example``을 복사합니다. 이는 사용자가 실행을 위해 복사-붙여넣기할 것으로 예상되는 튜토리얼 예제에 유용할 수 있습니다. 아래에서 이 동작을 시도해 볼 수 있습니다:

[source,console]
----
$ mkdir example
$ cd example
----