= UI 프로젝트 설정

UI 작업을 시작하기 전에 소스를 가져오고 프로젝트를 초기화해야 합니다. 소스는 Antora의 기본 UI이거나 Antora와 함께 작동하도록 구조화된 기존 UI 프로젝트일 수 있습니다.

== 기본 UI 프로젝트 가져오기

먼저, git을 사용하여 기본 UI 프로젝트를 클론합니다:

[source]
----
$ git clone https://gitlab.com/antora/antora-ui-default.git
$ cd "basename ${_%.git}"
----

위의 예제는 Antora의 기본 UI 프로젝트를 클론한 다음 파일 시스템의 프로젝트 폴더로 이동합니다. npm을 사용하여 프로젝트를 초기화하려면 이 프로젝트 폴더에 머물러 있어야 합니다.

=== 의존성 설치

다음으로 프로젝트를 초기화해야 합니다. 프로젝트 초기화는 기본적으로 의존성을 프로젝트에 다운로드하고 설치하는 것을 의미합니다. 이는 npm의 작업입니다.
터미널에서 다음 명령을 실행하세요(프로젝트 폴더 내에서):

[source]
----
$ npm i
----

npm i 명령어는 npm install의 축약형으로, __package.json__에 나열된 의존성을 프로젝트 내의 __node_modules/__ 폴더에 설치합니다. 이 폴더는 UI 번들에 포함되지 않습니다. 이 폴더는 안전하게 삭제할 수 있지만, npm이 이를 잘 관리합니다.

여기서 관련이 있어 보이는 또 다른 파일인 __package-lock.json__을 볼 수 있습니다. npm은 이 파일을 사용하여 어떤 구체적인 버전의 의존성을 사용할지 결정합니다. __package.json__의 버전은 일반적으로 범위일 뿐이기 때문입니다. 이 파일의 정보는 서로 다른 기계와 실행 간에 빌드를 재현 가능하게 만듭니다.

의존성을 설치하면 ``npx gulp`` 명령어를 사용할 수 있게 됩니다. Gulp 버전을 조회하여 이를 확인할 수 있습니다:

[source]
----
$ npx gulp -v
----

__package-lock.json__에 아직 나열되지 않은 새로운 의존성을 해결해야 하는 경우, ``npm i``를 실행하면 npm이 이 파일을 새로운 정보로 업데이트합니다. 따라서 __package-lock.json__ 파일이 변경될 때마다 저장소에 커밋하는 것이 좋습니다.

== 지원되는 빌드 작업

이제 의존성이 설치되었으므로 gulp 명령어를 실행하여 빌드가 지원하는 작업을 확인할 수 있습니다:

[source]
----
$ npx gulp --tasks-simple
----

다음과 같이 표시되어야 합니다:

[source]
----
default
clean
lint
format
build
bundle
bundle:pack
preview
preview:build
----

각 작업의 용도와 사용 시기에 대해 설명하겠습니다.