= 템플릿 커스터마이징

기본 UI 번들은 AsciiDoc 속성을 사용하여 사용자 정의할 수 있습니다. Work with the Handlebars Templates에서는 이러한 속성에 접근하는 방법을 설명합니다. 하지만 템플릿에서 실제로 사용되는 속성은 무엇일까요? 프로젝트에 기본 UI 번들을 사용할 계획이라면 이를 알고 싶을 것입니다.

== page-role 속성

page-role 속성은 일반적으로 페이지별로 정의됩니다. 이 속성은 해당 페이지의 <body> 태그에 하나 이상의 공백으로 구분된 클래스를 추가하는 데 사용됩니다.

page-role 속성의 일반적인 용도는 홈 페이지를 레이블링하는 것입니다.

[source,asciidoc]
----
= Home
:page-role: home

This is the home page.
----

결과 HTML에는 다음과 같은 <body> 시작 태그가 포함됩니다:

[source,html]
----
<body class="article -toc">
----

이제 스타일시트는 이 아이덴티티를 활용하여 특정 역할을 가진 페이지에 스타일을 할당할 수 있습니다. 예를 들어, 홈 페이지는 종종 다른 모양이 필요합니다. CSS로 해당 페이지를 대상으로 지정할 수 있으면 UI 개발자가 이러한 사용자 정의를 적용할 수 있습니다.

UI 템플릿이 페이지 역할을 다른 방식으로 사용할 수 있다는 점에 유의하세요. 현재 기본 UI는 <body> 태그의 class 속성에 값을 추가하는 것만 합니다.

=== TOC 사이드바 숨기기

기본 UI가 인식하는 하나의 예약된 페이지 역할은 -toc입니다. 이 역할은 사이트 스크립트에 TOC 사이드바를 제거(즉, 숨김)하도록 지시합니다. 다음은 설정 방법입니다.

[source,asciidoc]
----
= Page Title
:page-role: -toc

이 페이지에 섹션이 있어도 TOC 사이드바는 표시되지 않습니다.


== First Section

== Second Section
----

AsciiDoc toc 속성은 TOC가 기사 본문에 렌더링되는지 여부를 제어합니다. 기본 UI가 대체 TOC를 제공하므로 Antora를 사용할 때는 AsciiDoc의 내장 TOC 기능을 활성화하고 싶지 않을 것입니다.

== page-pagination 속성

``page-pagination`` 속성은 UI 번들이 지원하는 경우 페이지네이션을 활성화하기 위해 플레이북에서 설정됩니다. 기본 UI 번들은 이를 지원하며, 내비게이션을 기반으로 모든 페이지 하단에 이전 및 다음 페이지 링크가 표시됩니다.

=== 페이지네이션 활성화

[source,yaml]
----
asciidoc:
  attributes:
    page-pagination: ''
----

Antora는 자동으로 적절한 URL을 계산하고 올바른 링크를 삽입합니다.

사이트의 모든 페이지에 대해 이 기능을 활성화하려는 경우가 대부분이므로 페이지별로 이 속성을 설정할 필요가 없습니다. 그러나 페이지별로 재정의하려는 경우(예: 비활성화)에는 플레이북에서 값을 소프트 설정해야 합니다.

.페이지네이션 활성화, 재정의 가능
[source,yaml]
----
asciidoc:
  attributes:
    page-pagination: '@'
----

이제 문서 헤더에서 page-pagination 속성을 해제하여 페이지 페이지네이션을 끌 수 있습니다.